// A curated (not exhaustive) emoji set for gear-item thumbnails, weighted
// toward camping/hunting/outdoor gear with a general tail for everything
// else. Keywords are matched as substrings against the search query in
// EmojiPickerSheet -- plain text, not a real emoji database, so this is
// meant to cover the common cases well rather than be complete.
export const EMOJI_LIST: { emoji: string; keywords: string }[] = [
  // Shelter / camp
  { emoji: '⛺', keywords: 'tent camp camping shelter' },
  { emoji: '🏕️', keywords: 'camping tent camp' },
  { emoji: '🛖', keywords: 'hut cabin shelter' },
  { emoji: '🏠', keywords: 'house home' },
  { emoji: '🏡', keywords: 'house cabin home' },
  { emoji: '🎪', keywords: 'tent circus canopy' },
  { emoji: '🔥', keywords: 'fire campfire flame' },
  { emoji: '🪵', keywords: 'wood log firewood' },
  { emoji: '🧯', keywords: 'fire extinguisher safety' },

  // Sleep
  { emoji: '🛏️', keywords: 'bed sleep mattress' },
  { emoji: '🛌', keywords: 'sleeping bag bed' },
  { emoji: '😴', keywords: 'sleep tired' },
  { emoji: '💤', keywords: 'sleep zzz' },
  { emoji: '🪢', keywords: 'rope knot cord' },

  // Tools
  { emoji: '🪓', keywords: 'axe hatchet tool' },
  { emoji: '🔪', keywords: 'knife blade' },
  { emoji: '🧰', keywords: 'toolbox tools' },
  { emoji: '🔧', keywords: 'wrench tool' },
  { emoji: '🔨', keywords: 'hammer tool' },
  { emoji: '🪛', keywords: 'screwdriver tool' },
  { emoji: '🪚', keywords: 'saw tool' },
  { emoji: '⛏️', keywords: 'pickaxe pick tool' },
  { emoji: '🧲', keywords: 'magnet' },
  { emoji: '🪜', keywords: 'ladder' },
  { emoji: '⚙️', keywords: 'gear settings mechanical' },
  { emoji: '🔗', keywords: 'chain link' },
  { emoji: '🪝', keywords: 'hook' },

  // Navigation / electronics
  { emoji: '🧭', keywords: 'compass navigation direction' },
  { emoji: '🗺️', keywords: 'map' },
  { emoji: '🔦', keywords: 'flashlight torch light' },
  { emoji: '🏮', keywords: 'lantern light' },
  { emoji: '🔋', keywords: 'battery power' },
  { emoji: '🔌', keywords: 'plug charger power' },
  { emoji: '📱', keywords: 'phone cell mobile' },
  { emoji: '📻', keywords: 'radio' },
  { emoji: '📡', keywords: 'antenna signal satellite' },
  { emoji: '🛰️', keywords: 'satellite gps' },
  { emoji: '🔭', keywords: 'telescope scope' },
  { emoji: '🔍', keywords: 'magnify search lookup' },
  { emoji: '⏰', keywords: 'alarm clock time' },
  { emoji: '🕰️', keywords: 'clock time' },
  { emoji: '🌡️', keywords: 'thermometer temperature' },

  // Clothing
  { emoji: '🥾', keywords: 'boot hiking shoe' },
  { emoji: '👟', keywords: 'shoe sneaker' },
  { emoji: '🧤', keywords: 'glove gloves mitten' },
  { emoji: '🧦', keywords: 'sock socks' },
  { emoji: '🧥', keywords: 'jacket coat' },
  { emoji: '👕', keywords: 'shirt tshirt' },
  { emoji: '👖', keywords: 'pants jeans trousers' },
  { emoji: '🩳', keywords: 'shorts' },
  { emoji: '🧣', keywords: 'scarf' },
  { emoji: '🧢', keywords: 'hat cap' },
  { emoji: '👒', keywords: 'hat sunhat' },
  { emoji: '🕶️', keywords: 'sunglasses glasses' },
  { emoji: '⛑️', keywords: 'helmet hardhat' },

  // Water / cooking
  { emoji: '💧', keywords: 'water drop' },
  { emoji: '🚰', keywords: 'water faucet tap' },
  { emoji: '🧊', keywords: 'ice cube cold' },
  { emoji: '🍳', keywords: 'cooking pan fry' },
  { emoji: '🍲', keywords: 'pot stew cooking' },
  { emoji: '🥄', keywords: 'spoon utensil' },
  { emoji: '🍴', keywords: 'fork knife utensil' },
  { emoji: '🔥', keywords: 'stove fire heat' },
  { emoji: '☕', keywords: 'coffee drink' },
  { emoji: '🍵', keywords: 'tea drink' },

  // Safety / first aid
  { emoji: '🩹', keywords: 'bandage firstaid medical' },
  { emoji: '💊', keywords: 'pill medicine' },
  { emoji: '🧴', keywords: 'lotion sunscreen bottle' },
  { emoji: '🧼', keywords: 'soap wash hygiene' },
  { emoji: '🪥', keywords: 'toothbrush hygiene' },
  { emoji: '🧻', keywords: 'toilet paper' },
  { emoji: '🚨', keywords: 'alert siren emergency' },
  { emoji: '⚠️', keywords: 'warning caution' },
  { emoji: '🆘', keywords: 'sos help emergency' },

  // Hunting / fishing
  { emoji: '🏹', keywords: 'bow arrow archery' },
  { emoji: '🔫', keywords: 'gun rifle weapon' },
  { emoji: '🎯', keywords: 'target dart bullseye' },
  { emoji: '🐗', keywords: 'boar hog pig hunt' },
  { emoji: '🦌', keywords: 'deer elk hunt' },
  { emoji: '🐻', keywords: 'bear' },
  { emoji: '🦃', keywords: 'turkey bird' },
  { emoji: '🐇', keywords: 'rabbit bunny' },
  { emoji: '🐟', keywords: 'fish fishing' },
  { emoji: '🎣', keywords: 'fishing pole rod' },
  { emoji: '🐾', keywords: 'paw print animal tracks' },

  // Storage / misc gear
  { emoji: '🎒', keywords: 'backpack pack bag' },
  { emoji: '🧳', keywords: 'luggage suitcase bag' },
  { emoji: '🧺', keywords: 'basket' },
  { emoji: '🪣', keywords: 'bucket' },
  { emoji: '🗑️', keywords: 'trash garbage' },
  { emoji: '⛽', keywords: 'fuel gas' },
  { emoji: '🛢️', keywords: 'oil barrel' },
  { emoji: '🧵', keywords: 'thread sewing string' },
  { emoji: '🪡', keywords: 'needle sewing' },
  { emoji: '🧶', keywords: 'yarn wool' },
  { emoji: '🔑', keywords: 'key' },
  { emoji: '🔒', keywords: 'lock' },
  { emoji: '🪨', keywords: 'rock stone' },
  { emoji: '🧱', keywords: 'brick' },

  // Vehicles
  { emoji: '🚗', keywords: 'car vehicle truck' },
  { emoji: '🚙', keywords: 'suv truck vehicle' },
  { emoji: '🚚', keywords: 'truck vehicle' },
  { emoji: '🏍️', keywords: 'motorcycle bike' },
  { emoji: '🚲', keywords: 'bike bicycle' },
  { emoji: '🛶', keywords: 'canoe kayak boat' },
  { emoji: '🚤', keywords: 'boat speedboat' },
  { emoji: '⛵', keywords: 'sailboat boat sail' },
  { emoji: '✈️', keywords: 'plane airplane' },
  { emoji: '🚁', keywords: 'helicopter' },

  // Terrain / weather
  { emoji: '🌲', keywords: 'tree pine evergreen forest' },
  { emoji: '🌳', keywords: 'tree forest' },
  { emoji: '🍃', keywords: 'leaf leaves' },
  { emoji: '🍂', keywords: 'leaf fall autumn' },
  { emoji: '🌾', keywords: 'wheat grain field' },
  { emoji: '🌵', keywords: 'cactus desert' },
  { emoji: '🦋', keywords: 'butterfly' },
  { emoji: '🐝', keywords: 'bee insect' },
  { emoji: '🕷️', keywords: 'spider' },
  { emoji: '🐍', keywords: 'snake' },
  { emoji: '🦉', keywords: 'owl bird' },
  { emoji: '🦅', keywords: 'eagle bird hawk' },
  { emoji: '🌊', keywords: 'wave water ocean' },
  { emoji: '❄️', keywords: 'snow snowflake cold' },
  { emoji: '☀️', keywords: 'sun sunny' },
  { emoji: '⛅', keywords: 'cloud partly sunny' },
  { emoji: '🌧️', keywords: 'rain' },
  { emoji: '⛈️', keywords: 'storm thunder' },
  { emoji: '🌫️', keywords: 'fog mist' },
  { emoji: '🗻', keywords: 'mountain fuji' },
  { emoji: '⛰️', keywords: 'mountain' },
  { emoji: '🏔️', keywords: 'mountain snow' },
  { emoji: '🏞️', keywords: 'national park scenery' },
  { emoji: '🏜️', keywords: 'desert' },
  { emoji: '🏖️', keywords: 'beach' },

  // General / common
  { emoji: '⭐', keywords: 'star favorite' },
  { emoji: '❤️', keywords: 'heart love' },
  { emoji: '👍', keywords: 'thumbs up good' },
  { emoji: '✅', keywords: 'check done complete' },
  { emoji: '❌', keywords: 'no cross wrong' },
  { emoji: '🆕', keywords: 'new' },
  { emoji: '🏆', keywords: 'trophy award' },
  { emoji: '🥇', keywords: 'medal award gold' },
  { emoji: '📦', keywords: 'box package' },
  { emoji: '🏷️', keywords: 'tag label' },
];
